version: "3.7"
services:
  reverseproxy:
    build:
      context: ./nginx
      dockerfile: Dockerfile.nginx
    ports:
      - "443:443"
      - "80:80"
    restart: always
  keycloak:
    depends_on:
      - reverseproxy
    image: quay.io/keycloak/keycloak:18.0.0
    command: start-dev --import-realm --proxy edge
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      - ./keycloak-data:/opt/keycloak/data/import
