import {
  AuthenticatedTemplate,
  UnauthenticatedTemplate,
  useMsal,
} from "@azure/msal-react";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const { instance, accounts } = useMsal();
  const name = accounts[0] && accounts[0].name;

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to our super secure app!</h1>

        <div className={styles.grid}>
          <UnauthenticatedTemplate>
            <button
              onClick={() => instance.loginPopup()}
              className={styles.card}
            >
              Sign in
            </button>
          </UnauthenticatedTemplate>
          <AuthenticatedTemplate>
            <p className={styles.description}>Good to see you, {name}</p>
          </AuthenticatedTemplate>
        </div>
      </main>
    </div>
  );
};

export default Home;
